version: "3.8"

services:
  openresty-gateway:
    image: openresty/openresty:alpine
    container_name: openresty-gateway
    volumes:
      - ./openresty/conf:/usr/local/openresty/nginx/conf
      - ./openresty/lua:/usr/local/openresty/lualib
      - ./openresty/certs:/etc/nginx/certs
    ports:
      - "443:443"
    depends_on:
      - api-gateway

  api-gateway:
    image: node:16-alpine
    container_name: api-gateway
    working_dir: /app
    volumes:
      - ./api-gateway:/app
<<<<<<< HEAD
      - ./logs/api-gateway:/app/logs
=======
      - ./logs/api-gateway:/app/logs # Logs persistentes do gateway
>>>>>>> auth-service
    command: ["npm", "start"]
    restart: always
    expose:
      - "3000"
    depends_on:
      - auth-service
      - policy-service
      - resource-service
    environment:
      - NODE_ENV=production
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M

  auth-service:
    image: node:16-alpine
    container_name: auth-service
    working_dir: /app
    volumes:
      - ./auth-service:/app
<<<<<<< HEAD
      - ./logs/auth-service:/app/logs
=======
      - ./logs/auth-service:/app/logs # Logs persistentes da autenticação
>>>>>>> auth-service
    command: ["npm", "start"]
    restart: always
    expose:
      - "3001"
    ports:
      - "4000:3001"
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://university_user:securepass123@mongodb:27017/ztadb?authSource=ztadb
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M

  policy-service:
    image: node:16-alpine
    container_name: policy-service
    working_dir: /app
    volumes:
      - ./policy-service:/app
<<<<<<< HEAD
      - ./logs/policy-service:/app/logs
=======
      - ./logs/policy-service:/app/logs # Logs persistentes do policy
>>>>>>> auth-service
    command: ["npm", "start"]
    restart: always
    expose:
      - "3002"
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://university_user:securepass123@mongodb:27017/ztadb?authSource=ztadb
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M

  resource-service:
    image: node:16-alpine
    container_name: resource-service
    working_dir: /app
    volumes:
      - ./resource-service:/app
<<<<<<< HEAD
      - ./logs/resource-service:/app/logs
      - ./uploads/resource-service:/app/uploads
=======
      - ./logs/resource-service:/app/logs # Logs persistentes do resource
      - ./uploads/resource-service:/app/uploads # Persistência para uploads (se usar)
>>>>>>> auth-service
    command: ["npm", "start"]
    restart: always
    expose:
      - "3003"
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://university_user:securepass123@mongodb:27017/ztadb?authSource=ztadb
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
<<<<<<< HEAD
=======
    volumes:
      - ./mongo-data:/data/db # Persistência do banco de dados
      - ./mongo-config:/data/configdb # Persistência de configurações do Mongo (opcional)
>>>>>>> auth-service
    environment:
      - MONGO_INITDB_ROOT_USERNAME=adminroot
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
      - MONGO_INITDB_DATABASE=ztadb
<<<<<<< HEAD
    volumes:
      - ./mongo-data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
=======
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1G
>>>>>>> auth-service

  monitoring:
    image: node:16-alpine
    container_name: monitoring
    working_dir: /app
    volumes:
      - ./monitoring:/app
<<<<<<< HEAD
      - ./logs/monitoring:/app/logs
=======
      - ./logs/monitoring:/app/logs # Logs persistentes do monitoring
>>>>>>> auth-service
    command: ["npm", "start"]
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://university_user:securepass123@mongodb:27017/ztadb?authSource=ztadb
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 256M

networks:
  default:
    name: zta-network

volumes:
  mongo-data:
  mongo-config:
